### ISSUE TITLE
why I can't replicate your result?

### ISSUE THREAD

**Issue by leolle** [Spenhouet/automated-deep-photo-style-transfer#5]
![final_transfer_image](https://user-images.githubusercontent.com/12882642/57420862-0ccee280-723c-11e9-864f-eac95bae76ad.png)
This is what I get from the bear picture.

**Comment by Spenhouet** [comment]
Hi @leolle 

The example images are not produced with the default parameters.
We added a commit to expose the similarity metric as parameter.
I do not have the parameters at hand that we used when we produced the images but I did just run it again.

Please try the following extra parameters:

```
 --style_weight 5000
 --nima_weight 0
 --semantic_thresh 0.4
 --similarity_metric "wpath"
 --init "noise"
```

Make sure that before you start the new run you deleted the old segmentation masks.

Running with the above parameters should give this result:

![final_transfer_image](https://user-images.githubusercontent.com/7819068/57443440-59bbb480-724e-11e9-9b19-66af5f70a44a.png)

and these two segmentation masks:

![style_seg](https://user-images.githubusercontent.com/7819068/57443482-6f30de80-724e-11e9-82ff-6279af2a695a.png)
![content_seg](https://user-images.githubusercontent.com/7819068/57443483-6fc97500-724e-11e9-8e2e-23a533fff4bf.png)
