### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by siyas13** [Spenhouet/automated-deep-photo-style-transfer#7]
For the time I was running your project in python 3.5 but throws an error in sematch library as follows.
from sematch.semantic.similarity import WordNetSimilarity
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\Siyas\AppData\Local\Continuum\anaconda3\lib\site-packages\sematch\semantic\similarity.py", line 25, in 
from sematch.semantic.sparql import EntityFeatures, StatSPARQL
File "C:\Users\Siyas\AppData\Local\Continuum\anaconda3\lib\site-packages\sematch\semantic\sparql.py", line 36
print query
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print query)?

The fix was to give a parenthesis to that file specified. But thats not the fix. Please tell me how did it work for you.

**Comment by Spenhouet** [comment]
Yes, that is an issue. I did also solve it the same way as you did.
See this old issue that is still unresolved: https://github.com/gsi-upm/sematch/issues/18
I have no influence on the sematch repository so I can not do anything about that :/ sorry

**Comment by siyas13** [comment]
Yeah i know but try solving it in your code finding an alternative for sematch(if possible).  Another thing is that I couldn't reproduce a good result as you gave in the sample. Can you suggest some arguments for producing a better output? Also, memory usage is very high as it uses more that 10GB of RAM for images of size 600KB to 900KB. I suggest you optimize the code to efficient memory utilization.
