### ISSUE TITLE
Document for parameters? 

### ISSUE THREAD

**Issue by stanwtang** [Spenhouet/automated-deep-photo-style-transfer#8]
Is there any example of how to use style_transfer? Perhaps an explanation on the parameters as well. Thanks!

**Comment by Spenhouet** [comment]
Did you take a look at the arguments of the `style_transfer.py` script here?: https://github.com/Spenhouet/automated-deep-photo-style-transfer/blob/54020268f79c94c9d86364a2014b987fc5549d89/style_transfer.py#L236

If you need further explanations on the parameters you might want to take a look at our paper:  [Automated Deep Photo Style Transfer](https://arxiv.org/abs/1901.03915)

**Comment by stanwtang** [comment]
Just finished reading your paper, great work! I'm running Tensorflow 2 and python 3.7, so looks like I will have to clean out the errors for this to work

**Comment by Spenhouet** [comment]
This could be quite some work.
Feel free to fork and open a pull request when you are done.
